### PR TITLE
add 2023 Hero to homepage

### PR DESCRIPTION
**Pull request by aniketgargya**

### CODE REVIEW

**Comment by aniketgargya** [comment]
@ashayp22 Let me know if this looks good to push to deployment?

**Comment by ashayp22** [comment]
@aniketgargya 

Figma
Screenshot 2023-01-09 at 1 29 39 PM

Preview
Screenshot 2023-01-09 at 1 29 57 PM

Are you planning on adding this from the Figma?

**Comment by aniketgargya** [comment]
> @aniketgargya
> 
> Figma Screenshot 2023-01-09 at 1 29 39 PM
> 
> Preview Screenshot 2023-01-09 at 1 29 57 PM
> 
> Are you planning on adding this from the Figma?

Yup, added it now.

**Comment by ashayp22** [comment]
New deployment
Screenshot 2023-01-09 at 9 35 16 PM

Figma
Screenshot 2023-01-09 at 1 29 39 PM

Are you planning on adding the tiny star/bubble icons as well?

**Comment by aniketgargya** [comment]
> New deployment Screenshot 2023-01-09 at 9 35 16 PM
> 
> Figma Screenshot 2023-01-09 at 1 29 39 PM
> 
> Are you planning on adding the tiny star/bubble icons as well?

I was going to add this along with the next section, because this overlaps both the Hero and Event section.

**Comment by ashayp22** [comment]
Sounds good

**Review by ashayp22 — APPROVED** [review]

**Pull request merged**
