### PR TITLE
Application Status Page

### PR DESCRIPTION
**Pull request by miguelaenlle**
image

- Implemented Application Status page at /register/application-status
- User is automatically redirected to /register/sign-up-as if they haven't completed the form
- Removed "View Form" and "RSVP" buttons
- /register/sign-up-as, /register/challenge, and /register pages redirect to /register/application-status page

### CODE REVIEW

**Review by J164 — CHANGES_REQUESTED** [review]
Awesome work on this! Now that we have designs on the figma, can we add those too? (make sure to fetch and pull your branch because I made some minor adjustments)

**Comment by miguelaenlle** [comment]
> Awesome work on this! Now that we have designs on the figma, can we add those too? (make sure to fetch and pull your branch because I made some minor adjustments)

Yes -- I'll start working on these

**Comment by miguelaenlle** [comment]
> Awesome work on this! Now that we have designs on the figma, can we add those too? (make sure to fetch and pull your branch because I made some minor adjustments)

@J164 , I implemented the Figma designs on the Application Status page:

image

They're also mobile-optimized:

image

The only issue is that the rain in the SVG background appears black. Let me know if you have any ideas on how to fix it, or if this is okay.

**Comment by miguelaenlle** [comment]
The latest commit resolved the Application Status Background issue:

image

**Review by J164 — APPROVED** [review]
Looks great!

**Pull request merged**
