### PR TITLE
Events page

### PR DESCRIPTION
**Pull request by aniketgargya**

### CODE REVIEW

**Review by nrking0 — COMMENTED** [review]
Do we have a plan for mobile? 

image

**Comment by aniketgargya** [comment]
@nrking0 will change this, but plan to ship now just to get it at least available on mobile

**Review by nrking0 — APPROVED** [review]
Sounds good, I would just add nav button then should be good to merge

**Comment by ashayp22** [comment]
Doing this right now.

**Review by ashayp22 — APPROVED** [review]

**Pull request merged**
